<?php

/**
 *------
 * BGA framework: © Gregory Isabelli <gisabelli@boardgamearena.com> & Emmanuel Colin <ecolin@boardgamearena.com>
 * WizardsGrimoire implementation : © Martin Goulet <martin.goulet@live.ca>
 * 
 * This code has been produced on the BGA studio platform for use on http://boardgamearena.com.
 * See http://en.boardgamearena.com/#!doc/Studio for more information.
 * -----
 *
 * material.inc.php
 *
 * WizardsGrimoire game material description
 *
 * Here, you can describe the material of your game with PHP variables.
 *   
 * This file is loaded in your game logic class constructor, ie these variables
 * are available everywhere in your game logic code.
 *
 */


$this->card_types = [
  1 => [
    "name" => clienttranslate("Touch the void"),
    "class" => "TouchTheVoid",
    "description" => clienttranslate("Deal damage equal to the quantity of mana cards on 1 of your spells"),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_BEGINNER,
  ],
  2 => [
    "name" => clienttranslate("Overload"),
    "class" => "Overload",
    "description" => clienttranslate("Deal damage equal to the quantity of mana cards on 1 of your opponent's spell"),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_BEGINNER,
  ],
  3 => [
    "name" => clienttranslate("Mutation"),
    "class" => "Mutation",
    "description" => clienttranslate("Gain 1 mana card. Deal damage equal to that mana's power"),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_BEGINNER,
  ],
  4 => [
    "name" => clienttranslate("Stone crush"),
    "class" => "StoneCrush",
    "description" => clienttranslate("Deal 1 damage for each mana card in your opponent's hand"),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_BEGINNER,
  ],
  5 => [
    "name" => clienttranslate("Mist of pain"),
    "class" => "MistOfPain",
    "description" => clienttranslate("Your opponent may discard up to 4 mana cards from their hand. For each mana they do not discard, deal 1 damage"),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_BEGINNER,
  ],
  6 => [
    "name" => clienttranslate("Arcane tactics"),
    "class" => "ArcaneTactics",
    "description" => clienttranslate("Gain 7 mana cards from the mana deck. Then place 4 mana cards from your hand on top of the mana deck in any order"),
    "type" => WG_SPELL_TYPE_REGENERATION,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_BEGINNER,
  ],
  7 => [
    "name" => clienttranslate("Freeze"),
    "class" => "Freeze",
    "description" => clienttranslate("Choose 1:  Gain 4 mana cards, or place a mana card from the mana deck on one of your opponent's spells"),
    "type" => WG_SPELL_TYPE_REGENERATION,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_BEGINNER,
  ],
  8 => [
    "name" => clienttranslate("Energy reserve"),
    "class" => "EnergyReserve",
    "description" => clienttranslate("Pick up a mana card off 1 of your others spells. Gain mana equal to that mana's power."),
    "type" => WG_SPELL_TYPE_REGENERATION,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_BEGINNER,
  ],
  9 => [
    "name" => clienttranslate("Fracture"),
    "class" => "Fracture",
    "description" => clienttranslate("Gain 4 mana cards. You may move a mana card between 2 of your other spells"),
    "type" => WG_SPELL_TYPE_REGENERATION,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_BEGINNER,
    "js_actions" => ["actionSelectManaFrom", "actionSelectManaTo"],
  ],
  10 => [
    "name" => clienttranslate("Gleam of hope"),
    "class" => "GleamOfHope",
    "description" => clienttranslate("Gain mana until you have 5 mana cards in your hand"),
    "type" => WG_SPELL_TYPE_REGENERATION,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_BEGINNER,
  ],

  11 => [
    "name" => clienttranslate("Rejuvenation"),
    "class" => "Rejuvenation",
    "description" => clienttranslate("Choose 1: Gain 4 mana cards, or take 2 mana cards of any power from the discard pile."),
    "type" => WG_SPELL_TYPE_REGENERATION,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_BEGINNER,
  ],
  12 => [
    "name" => clienttranslate("Shackled motion"),
    "class" => "ShackledMotion",
    "description" => clienttranslate("Choose 1: Gain 4 mana cards, or your opponent must discard their hand"),
    "type" => WG_SPELL_TYPE_REGENERATION,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_BEGINNER,
  ],
  13 => [
    "name" => clienttranslate("Living wind"),
    "class" => "LivingWind",
    "description" => clienttranslate("Gain 6 mana cards, gain 1 fewer mana for each of your other spells that have a mana on them"),
    "type" => WG_SPELL_TYPE_REGENERATION,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_BEGINNER,
  ],
  14 => [
    "name" => clienttranslate("Coercive agreement"),
    "class" => "CoerciveAgreement",
    "description" => clienttranslate("Choose 1: Take up to 3 randomly selected mana from your opponent's hand, or discard a mana card off 2 of your other spells."),
    "type" => WG_SPELL_TYPE_UTILITY,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_INTERMEDIATE,
  ],

  15 => [
    "name" => clienttranslate("Arcane eye"),
    "class" => "ArcaneEye",
    "description" => clienttranslate("Pick up a mana card of each of your spells that costs 3 or more"),
    "type" => WG_SPELL_TYPE_UTILITY,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_INTERMEDIATE,
  ],
  16 => [
    "name" => clienttranslate("Haste"),
    "class" => "Haste",
    "description" => clienttranslate("The next time you cast a spell this turn, it costs 2 less."),
    "type" => WG_SPELL_TYPE_UTILITY,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_BEGINNER,
  ],
  17 => [
    "name" => clienttranslate("Renewed fervor"),
    "class" => "RenewedFervor",
    "description" => clienttranslate("Pick up a mana card off each of your instant attack spells that costs 2 or less."),
    "type" => WG_SPELL_TYPE_UTILITY,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_BEGINNER,
  ],
  18 => [
    "name" => clienttranslate("Secret Oath"),
    "class" => "SecretOath",
    "description" => clienttranslate("As long as this spell has mana on it, if your opponent has a 4 power mana in their hand, they must give it to you immediately"),
    "type" => WG_SPELL_TYPE_UTILITY,
    "activation" => WG_SPELL_ACTIVATION_ONGOING,
    "cost" => 2,
    "icon" => WG_ICON_INTERMEDIATE,
  ],
  19 => [
    "name" => clienttranslate("Time distortion"),
    "class" => "TimeDistortion",
    "description" => clienttranslate("Pick up a mana card of 2 of your other spells"),
    "type" => WG_SPELL_TYPE_UTILITY,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_BEGINNER,
    "js_actions" => "actionTimeDistortion",
  ],
  20 => [
    "name" => clienttranslate("Betrayal"),
    "class" => "Betrayal",
    "description" => clienttranslate("Deal 5 damage. Your opponent gains 3 mana cards."),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 3,
    "icon" => WG_ICON_BEGINNER,
  ],

  21 => [
    "name" => clienttranslate("Blood lust"),
    "class" => "BloodLust",
    "description" => clienttranslate("Deal 1 damage. Deal an additionnal 2 damage for each attack spell cast consecutively before this spell"),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 3,
    "icon" => WG_ICON_INTERMEDIATE,
  ],
  22 => [
    "name" => clienttranslate("Delusion"),
    "class" => "Delusion",
    "description" => clienttranslate("Deal 3 damage. You may pick up a mana card off 1 of your opponent's spells"),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 3,
    "icon" => WG_ICON_INTERMEDIATE,
  ],
  23 => [
    "name" => clienttranslate("Vile laughter"),
    "class" => "VileLaughter",
    "description" => clienttranslate("Deal 6 damage, minus the highest power mana in your hand"),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 3,
    "icon" => WG_ICON_BEGINNER,
  ],
  24 => [
    "name" => clienttranslate("Doom drop"),
    "class" => "DoomDrop",
    "description" => clienttranslate("Each time a mana card is discarded of this spell, deal damage equal to that mana's power"),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_DELAYED,
    "cost" => 3,
    "icon" => WG_ICON_BEGINNER,
  ],

  25 => [
    "name" => clienttranslate("Energy storm"),
    "class" => "EnergyStorm",
    "description" => clienttranslate("Deal 3 damage. Deal 1 additional damage for each 4 power mana in your hand"),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 3,
    "icon" => WG_ICON_BEGINNER,
  ],
  26 => [
    "name" => clienttranslate("Fire blast"),
    "class" => "FireBlast",
    "description" => clienttranslate("Discard all mana in your hand. Deal 7 damage"),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 3,
    "icon" => WG_ICON_BEGINNER,
  ],
  27 => [
    "name" => clienttranslate("Painful vision"),
    "class" => "PainfulVision",
    "description" => clienttranslate("Deal 5 damage. Place a mana from the mana deck on all your spells with 1 mana card on them"),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 3,
    "icon" => WG_ICON_INTERMEDIATE,
  ],
  28 => [
    "name" => clienttranslate("Possessed"),
    "class" => "Possessed",
    "description" => clienttranslate("Deal 5 damage. Your opponent may give you a mana from their hand. If they do, reduce your damage by the mana's power"),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 3,
    "icon" => WG_ICON_INTERMEDIATE,
  ],
  29 => [
    "name" => clienttranslate("Second strike"),
    "class" => "SecondStrike",
    "description" => clienttranslate("Deal 3 damage. The next time you cast an attack spell this turn, it costs 1 less."),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 3,
    "icon" => WG_ICON_BEGINNER,
  ],
  30 => [
    "name" => clienttranslate("Trap attack"),
    "class" => "TrapAttack",
    "description" => clienttranslate("Pick up a mana card off 1 of your other spells. Deal damage equal to that mana's power"),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 3,
    "icon" => WG_ICON_BEGINNER,
  ],
  31 => [
    "name" => clienttranslate("Energy shield"),
    "class" => "EnergyShield",
    "description" => clienttranslate("Pick up a mana card off 1 of your other spells. Place a mana card from the mana deck on 1 of your opponent's spells."),
    "type" => WG_SPELL_TYPE_UTILITY,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 3,
    "icon" => WG_ICON_INTERMEDIATE,
  ],
  32 => [
    "name" => clienttranslate("Growth"),
    "class" => "Growth",
    "description" => clienttranslate("During your turn, increase the power of all mana by 1"),
    "type" => WG_SPELL_TYPE_UTILITY,
    "activation" => WG_SPELL_ACTIVATION_ONGOING,
    "cost" => 3,
    "icon" => WG_ICON_INTERMEDIATE,
  ],
  33 => [
    "name" => clienttranslate("Fury"),
    "class" => "Fury",
    "description" => clienttranslate("Deal 1 damage for each of your opponent's spells that have mana on them"),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 4,
    "icon" => WG_ICON_BEGINNER,
  ],
  34 => [
    "name" => clienttranslate("Hellstorm"),
    "class" => "Hellstorm",
    "description" => clienttranslate("Gain 5 mana cards. Deal damage equal to the highest power mana you gain"),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 4,
    "icon" => WG_ICON_BEGINNER,
  ],


  35 => [
    "name" => clienttranslate("Shadow attack"),
    "class" => "ShadowAttack",
    "description" => clienttranslate("Discard a mana card off 1 of your other spells. Deal damage and gain mana equal to that mana's power"),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 4,
    "icon" => WG_ICON_BEGINNER,
    "js_actions" => "actionShadowAttack",
  ],
  36 => [
    "name" => clienttranslate("Crushing blow"),
    "class" => "CrushingBlow",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 5,
    "icon" => WG_ICON_BEGINNER,
  ],
  37 => [
    "name" => clienttranslate("False face"),
    "class" => "FalseFace",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_ONGOING,
    "cost" => 1,
    "icon" => WG_ICON_ADVANCE,
  ],
  38 => [
    "name" => clienttranslate("Quick swap"),
    "class" => "QuickSwap",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_UTILITY,
    "activation" => WG_SPELL_ACTIVATION_DELAYED,
    "cost" => 1,
    "icon" => WG_ICON_ADVANCE,
  ],

  39 => [
    "name" => clienttranslate("Lullaby"),
    "class" => "Lullaby",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_REGENERATION,
    "activation" => WG_SPELL_ACTIVATION_ONGOING,
    "cost" => 1,
    "icon" => WG_ICON_ADVANCE,
  ],
  40 => [
    "name" => clienttranslate("Amnesia"),
    "class" => "Amnesia",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 1,
    "icon" => WG_ICON_ADVANCE,
  ],

  41 => [
    "name" => clienttranslate("Hoodwink"),
    "class" => "Hoodwink",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 3,
    "icon" => WG_ICON_ADVANCE,
  ],
  42 => [
    "name" => clienttranslate("Wild bloom"),
    "class" => "WildBloom",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_UTILITY,
    "activation" => WG_SPELL_ACTIVATION_DELAYED,
    "cost" => 2,
    "icon" => WG_ICON_ADVANCE,
  ],
  43 => [
    "name" => clienttranslate("Tsunami"),
    "class" => "Tsunami",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_ADVANCE,
  ],
  44 => [
    "name" => clienttranslate("Twist of fate"),
    "class" => "TwistOfFate",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 3,
    "icon" => WG_ICON_ADVANCE,
  ],


  45 => [
    "name" => clienttranslate("Fatal flaw"),
    "class" => "FatalFlaw",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_ADVANCE,
  ],
  46 => [
    "name" => clienttranslate("Affliction"),
    "class" => "Affliction",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_REGENERATION,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_ADVANCE,
  ],
  47 => [
    "name" => clienttranslate("Friendly truce"),
    "class" => "FriendlyTruce",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_REGENERATION,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_BEGINNER,
  ],
  48 => [
    "name" => clienttranslate("Windstorm"),
    "class" => "Windstorm",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 1,
    "icon" => WG_ICON_BEGINNER,
  ],

  49 => [
    "name" => clienttranslate("Guilty bond"),
    "class" => "GuiltyBond",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 1,
    "icon" => WG_ICON_BEGINNER,
  ],
  50 => [
    "name" => clienttranslate("Trance state"),
    "class" => "TranceState",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 1,
    "icon" => WG_ICON_INTERMEDIATE,
  ],

  51 => [
    "name" => clienttranslate("Renewal"),
    "class" => "Renewal",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_REGENERATION,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 1,
    "icon" => WG_ICON_BEGINNER,
  ],
  52 => [
    "name" => clienttranslate("Toxic gift"),
    "class" => "ToxicGift",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 1,
    "icon" => WG_ICON_BEGINNER,
  ],
  53 => [
    "name" => clienttranslate("Wrath"),
    "class" => "Wrath",
    "description" => clienttranslate("Your opponent may discard 2 mana cards from their hand. If they do not, deal 2 damage."),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 1,
    "icon" => WG_ICON_BEGINNER,
  ],
  54 => [
    "name" => clienttranslate("Reckless attack"),
    "class" => "RecklessAttack",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_DELAYED,
    "cost" => 1,
    "icon" => WG_ICON_INTERMEDIATE,
  ],


  55 => [
    "name" => clienttranslate("Shared power"),
    "class" => "SharedPower",
    "description" => clienttranslate("You may give your opponent 1 mana card from your hand. If you do, gain 4 mana cards"),
    "type" => WG_SPELL_TYPE_REGENERATION,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 1,
    "icon" => WG_ICON_BEGINNER,
    "js_actions" => "actionSharedPower",
  ],
  56 => [
    "name" => clienttranslate("Sleight of hand"),
    "class" => "SleightOfHand",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_REGENERATION,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 1,
    "icon" => WG_ICON_BEGINNER,
  ],
  57 => [
    "name" => clienttranslate("Soul pact"),
    "class" => "SoulPact",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_REGENERATION,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 1,
    "icon" => WG_ICON_INTERMEDIATE,
  ],
  58 => [
    "name" => clienttranslate("Mirror image"),
    "class" => "MirrorImage",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_REGENERATION,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 1,
    "icon" => WG_ICON_INTERMEDIATE,
  ],

  59 => [
    "name" => clienttranslate("Battle vision"),
    "class" => "BattleVision",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_UTILITY,
    "activation" => WG_SPELL_ACTIVATION_ONGOING,
    "cost" => 1,
    "icon" => WG_ICON_INTERMEDIATE,
  ],
  60 => [
    "name" => clienttranslate("Silent support"),
    "class" => "SilentSupport",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_UTILITY,
    "activation" => WG_SPELL_ACTIVATION_DELAYED,
    "cost" => 1,
    "icon" => WG_ICON_INTERMEDIATE,
  ],


  61 => [
    "name" => clienttranslate("Power hungry"),
    "class" => "PowerHungry",
    "description" => clienttranslate("Both players basic attack mana cards go to your hand instead of the discard pile"),
    "type" => WG_SPELL_TYPE_UTILITY,
    "activation" => WG_SPELL_ACTIVATION_ONGOING,
    "cost" => 1,
    "icon" => WG_ICON_BEGINNER,
  ],
  62 => [
    "name" => clienttranslate("Sneaky deal"),
    "class" => "SneakyDeal",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_UTILITY,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 1,
    "icon" => WG_ICON_BEGINNER,
  ],
  63 => [
    "name" => clienttranslate("Puppetmaster"),
    "class" => "Puppetmaster",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_UTILITY,
    "activation" => WG_SPELL_ACTIVATION_ONGOING,
    "cost" => 1,
    "icon" => WG_ICON_INTERMEDIATE,
  ],
  64 => [
    "name" => clienttranslate("Contamination"),
    "class" => "Contamination",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_INTERMEDIATE,
  ],

  65 => [
    "name" => clienttranslate("Dance of pain"),
    "class" => "DanceOfPain",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_INTERMEDIATE,
  ],
  66 => [
    "name" => clienttranslate("Drain soul"),
    "class" => "DrainSoul",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_BEGINNER,
  ],
  67 => [
    "name" => clienttranslate("Ice Storm"),
    "class" => "IceStorm",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_INTERMEDIATE,
  ],
  68 => [
    "name" => clienttranslate("AfterShock"),
    "class" => "AfterShock",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_INTERMEDIATE,
  ],

  69 => [
    "name" => clienttranslate("Bad fortune"),
    "class" => "BadFortune",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_BEGINNER,
  ],
  70 => [
    "name" => clienttranslate("Force of nature"),
    "class" => "ForceOfNature",
    "description" => clienttranslate(""),
    "type" => WG_SPELL_TYPE_DAMAGE,
    "activation" => WG_SPELL_ACTIVATION_INSTANT,
    "cost" => 2,
    "icon" => WG_ICON_INTERMEDIATE,
  ],
];

$this->mana_cards = [
  1 => 32,
  2 => 16,
  3 => 8,
  4 => 4,
];