<?php

/**
 *------
 * BGA framework: © Gregory Isabelli <gisabelli@boardgamearena.com> & Emmanuel Colin <ecolin@boardgamearena.com>
 * WizardsGrimoireExt implementation : © Martin Goulet <martin.goulet@live.ca>
 * 
 * This code has been produced on the BGA studio platform for use on http://boardgamearena.com.
 * See http://en.boardgamearena.com/#!doc/Studio for more information.
 * -----
 *
 * material.inc.php
 *
 * WizardsGrimoireExt game material description
 *
 * Here, you can describe the material of your game with PHP variables.
 *   
 * This file is loaded in your game logic class constructor, ie these variables
 * are available everywhere in your game logic code.
 *
 */


$this->card_types = [
  // --- gen php begin ---
 1 => [ 
  'name' => clienttranslate("Touch the void"),
  'class' => "TouchTheVoid",
  'description' => clienttranslate("Deal damage equal to the quantity of mana cards on 1 of your spells"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_1,
],
 2 => [ 
  'name' => clienttranslate("Overload"),
  'class' => "Overload",
  'description' => clienttranslate("Deal damage equal to the quantity of mana cards on 1 of your opponent's spell"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_1,
],
 3 => [ 
  'name' => clienttranslate("Mutation"),
  'class' => "Mutation",
  'description' => clienttranslate("Gain 1 mana card. Deal damage equal to that mana's power"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_1,
],
 4 => [ 
  'name' => clienttranslate("Stone crush"),
  'class' => "StoneCrush",
  'description' => clienttranslate("Deal 1 damage for each mana card in your opponent's hand"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_2,
],
 5 => [ 
  'name' => clienttranslate("Mist of pain"),
  'class' => "MistOfPain",
  'description' => clienttranslate("Your opponent may discard up to 4 mana cards from their hand. For each mana they do not discard, deal 1 damage"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_1,
  'interaction' => "opponent",
  'js_actions_interaction' => "actionMistOfPain",
],
 6 => [ 
  'name' => clienttranslate("Arcane tactics"),
  'class' => "ArcaneTactics",
  'description' => clienttranslate("Gain 7 mana cards from the mana deck. Then place 4 mana cards from your hand on top of the mana deck in any order"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_1,
  'interaction' => "player",
  'js_actions_interaction' => "actionArcaneTactics",
],
 7 => [ 
  'name' => clienttranslate("Freeze"),
  'class' => "Freeze",
  'description' => clienttranslate("Choose 1: Gain 4 mana cards, or place a mana card from the mana deck on one of your opponent's spells"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_1,
  'js_actions' => "actionFreeze",
],
 8 => [ 
  'name' => clienttranslate("Energy reserve"),
  'class' => "EnergyReserve",
  'description' => clienttranslate("Pick up a mana card off 1 of your other spells. Gain mana equal to that mana's power"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_1,
  'js_actions' => "actionEnergyReserve",
],
 9 => [ 
  'name' => clienttranslate("Fracture"),
  'class' => "Fracture",
  'description' => clienttranslate("Gain 4 mana cards. You may move a mana card between 2 of your other spells"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_2,
  'interaction' => "player",
  'js_actions_interaction' => "actionFracture",
],
 10 => [ 
  'name' => clienttranslate("Gleam of hope"),
  'class' => "GleamOfHope",
  'description' => clienttranslate("Gain mana until you have 5 mana cards in your hand"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_1,
],
 11 => [ 
  'name' => clienttranslate("Rejuvenation"),
  'class' => "Rejuvenation",
  'description' => clienttranslate("Choose 1: Gain 4 mana cards, or take 2 mana cards of any power from the discard pile"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_1,
  'js_actions' => "actionRejuvenation",
],
 12 => [ 
  'name' => clienttranslate("Shackled motion"),
  'class' => "ShackledMotion",
  'description' => clienttranslate("Choose 1: Gain 4 mana cards, or your opponent must discard their hand"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_1,
  'js_actions' => "actionShackledMotion",
],
 13 => [ 
  'name' => clienttranslate("Living wind"),
  'class' => "LivingWind",
  'description' => clienttranslate("Gain 6 mana cards, gain 1 fewer mana for each of your other spells that have a mana on them"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_1,
],
 14 => [ 
  'name' => clienttranslate("Coercive agreement"),
  'class' => "CoerciveAgreement",
  'description' => clienttranslate("Choose 1: Take up to 3 randomly selected mana from your opponent's hand, or discard a mana card off 2 of your other spells"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_2,
  'js_actions' => "actionCoerciveAgreement",
],
 15 => [ 
  'name' => clienttranslate("Arcane eye"),
  'class' => "ArcaneEye",
  'description' => clienttranslate("Pick up a mana card off each of your spells that costs 3 or more"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_2,
],
 16 => [ 
  'name' => clienttranslate("Haste"),
  'class' => "Haste",
  'description' => clienttranslate("The next time you cast a spell this turn, it costs 2 less"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_1,
],
 17 => [ 
  'name' => clienttranslate("Renewed fervor"),
  'class' => "RenewedFervor",
  'description' => clienttranslate("Pick up a mana card off each of your instant attack spells that costs 2 or less"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_1,
],
 18 => [ 
  'name' => clienttranslate("Secret oath"),
  'class' => "SecretOath",
  'description' => clienttranslate("As long as this spell has mana on it, if your opponent has a 4 power mana in their hand, they must give it to you immediately"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_ONGOING,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_2,
  'banned' => true,
],
 19 => [ 
  'name' => clienttranslate("Time distortion"),
  'class' => "TimeDistortion",
  'description' => clienttranslate("Pick up a mana card off 2 of your other spells"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_1,
  'js_actions' => "actionTimeDistortion",
],
 20 => [ 
  'name' => clienttranslate("Betrayal"),
  'class' => "Betrayal",
  'description' => clienttranslate("Deal 5 damage. Your opponent gains 3 mana cards"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_BASE_1,
],
 21 => [ 
  'name' => clienttranslate("Blood lust"),
  'class' => "BloodLust",
  'description' => clienttranslate("Deal 1 damage. Deal an additionnal 2 damage for each attack spell cast consecutively before this spell"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_BASE_2,
],
 22 => [ 
  'name' => clienttranslate("Delusion"),
  'class' => "Delusion",
  'description' => clienttranslate("Deal 3 damage. You may pick up a mana card off 1 of your opponent's spells"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_BASE_2,
  'js_actions' => "actionDelusion",
],
 23 => [ 
  'name' => clienttranslate("Vile laughter"),
  'class' => "VileLaughter",
  'description' => clienttranslate("Deal 6 damage, minus the highest power mana in your hand"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_BASE_1,
],
 24 => [ 
  'name' => clienttranslate("Doom drop"),
  'class' => "DoomDrop",
  'description' => clienttranslate("Each time a mana card is discarded of this spell, deal damage equal to that mana's power"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_DELAYED,
  'activation_auto' => true,
  'cost' => 3,
  'icon' => WG_ICON_SET_BASE_1,
],
 25 => [ 
  'name' => clienttranslate("Energy storm"),
  'class' => "EnergyStorm",
  'description' => clienttranslate("Deal 3 damage. Deal 1 additional damage for each 4 power mana in your hand"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_BASE_1,
],
 26 => [ 
  'name' => clienttranslate("Fire blast"),
  'class' => "FireBlast",
  'description' => clienttranslate("Discard all mana in your hand. Deal 7 damage"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_BASE_1,
],
 27 => [ 
  'name' => clienttranslate("Painful vision"),
  'class' => "PainfulVision",
  'description' => clienttranslate("Deal 5 damage. Place a mana from the mana deck on all your spells with 1 mana card on them"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_BASE_2,
],
 28 => [ 
  'name' => clienttranslate("Possessed"),
  'class' => "Possessed",
  'description' => clienttranslate("Deal 5 damage. Your opponent may give you a mana from their hand. If they do, reduce your damage by the mana's power"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_BASE_2,
  'interaction' => "opponent",
  'js_actions_interaction' => "actionPossessed",
],
 29 => [ 
  'name' => clienttranslate("Second strike"),
  'class' => "SecondStrike",
  'description' => clienttranslate("Deal 3 damage. The next time you cast an attack spell this turn, it costs 1 less"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_BASE_1,
],
 30 => [ 
  'name' => clienttranslate("Trap attack"),
  'class' => "TrapAttack",
  'description' => clienttranslate("Pick up a mana card off 1 of your other spells. Deal damage equal to that mana's power"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_BASE_1,
  'js_actions' => "actionTrapAttack",
],
 31 => [ 
  'name' => clienttranslate("Energy shield"),
  'class' => "EnergyShield",
  'description' => clienttranslate("Pick up a mana card off 1 of your other spells. Place a mana card from the mana deck on 1 of your opponent's spells"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_BASE_2,
  'js_actions' => "actionEnergyShield",
],
 32 => [ 
  'name' => clienttranslate("Growth"),
  'class' => "Growth",
  'description' => clienttranslate("During your turn, increase the power of all mana by 1"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_ONGOING,
  'cost' => 3,
  'icon' => WG_ICON_SET_BASE_2,
],
 33 => [ 
  'name' => clienttranslate("Fury"),
  'class' => "Fury",
  'description' => clienttranslate("Deal 1 damage for each of your opponent's spells that have mana on them"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 4,
  'icon' => WG_ICON_SET_BASE_1,
],
 34 => [ 
  'name' => clienttranslate("Hellstorm"),
  'class' => "Hellstorm",
  'description' => clienttranslate("Gain 5 mana cards. Deal damage equal to the highest power mana you gain"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 4,
  'icon' => WG_ICON_SET_BASE_1,
],
 35 => [ 
  'name' => clienttranslate("Shadow attack"),
  'class' => "ShadowAttack",
  'description' => clienttranslate("Discard a mana card off 1 of your other spells. Deal damage and gain mana equal to that mana's power"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 4,
  'icon' => WG_ICON_SET_BASE_1,
  'js_actions' => "actionShadowAttack",
],
 36 => [ 
  'name' => clienttranslate("Crushing blow"),
  'class' => "CrushingBlow",
  'description' => clienttranslate("Deal 6 damage"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 5,
  'icon' => WG_ICON_SET_BASE_1,
],
 37 => [ 
  'name' => clienttranslate("False face"),
  'class' => "FalseFace",
  'description' => clienttranslate("If you deal 1 or less damage during your basic attack phase, deal 3 damage when your turn ends"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_ONGOING,
  'cost' => 1,
  'icon' => WG_ICON_SET_KICKSTARTER_1,
],
 38 => [ 
  'name' => clienttranslate("Quick swap"),
  'class' => "QuickSwap",
  'description' => clienttranslate("Each time you discard off this spell, choose 1: deal 1 damage, or discard this spell and replace it with a new spell"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_DELAYED,
  'activation_auto' => false,
  'cost' => 1,
  'icon' => WG_ICON_SET_KICKSTARTER_1,
  'js_actions_delayed' => "actionQuickSwap",
],
 39 => [ 
  'name' => clienttranslate("Lullaby"),
  'class' => "Lullaby",
  'description' => clienttranslate("As long as there is mana on this spell, if you have 0 mana cards in your hand, gain 2 mana cards"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_ONGOING,
  'cost' => 1,
  'icon' => WG_ICON_SET_KICKSTARTER_1,
],
 40 => [ 
  'name' => clienttranslate("Amnesia"),
  'class' => "Amnesia",
  'description' => clienttranslate("Deal 1 damage. Deal 1 additional damage for each time this spell was cast previously this turn"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_KICKSTARTER_1,
],
 41 => [ 
  'name' => clienttranslate("Hoodwink"),
  'class' => "Hoodwink",
  'description' => clienttranslate("Deal 6 damage, minus the damage your opponent dealt their last basic attack phase"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_KICKSTARTER_1,
],
 42 => [ 
  'name' => clienttranslate("Wild bloom"),
  'class' => "WildBloom",
  'description' => clienttranslate("When you discard the last mana off this spell, you may immediately cast an instant spell of yours that has 0 mana on it for no cost"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_DELAYED,
  'activation_auto' => false,
  'cost' => 2,
  'icon' => WG_ICON_SET_KICKSTARTER_1,
  'js_actions_delayed' => "actionWildBloom",
],
 43 => [ 
  'name' => clienttranslate("Tsunami"),
  'class' => "Tsunami",
  'description' => clienttranslate("Gain 1 mana card. Deal 1 damage for each mana of a unique power in your hand"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_KICKSTARTER_1,
],
 44 => [ 
  'name' => clienttranslate("Twist of fate"),
  'class' => "TwistOfFate",
  'description' => clienttranslate("Deal 2 damage. You may discard and replace 1 of your other spells with a new spell. Move all mana on it onto the new spell"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_KICKSTARTER_1,
  'js_actions' => "actionTwistOfFate",
],
 45 => [ 
  'name' => clienttranslate("Fatal flaw"),
  'class' => "FatalFlaw",
  'description' => clienttranslate("Deal 1 damage. Reveal the top mana card on 1 of your opponents spells, dealing additional damage equal to it's power"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_KICKSTARTER_1,
  'js_actions' => "actionFatalFlaw",
],
 46 => [ 
  'name' => clienttranslate("Affliction"),
  'class' => "Affliction",
  'description' => clienttranslate("Gain 4 mana cards. You may deal 1 damage to yourself. If you do, gain 2 extra cards"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_KICKSTARTER_1,
  'interaction' => "player",
  'js_actions_interaction' => "actionAffliction",
],
 47 => [ 
  'name' => clienttranslate("Friendly truce"),
  'class' => "FriendlyTruce",
  'description' => clienttranslate("Your opponent may give you 3 cards from their hand. If they do not, gain 5 mana cards"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_1,
  'interaction' => "opponent",
  'js_actions_interaction' => "actionFriendlyTruce",
],
 48 => [ 
  'name' => clienttranslate("Windstorm"),
  'class' => "Windstorm",
  'description' => clienttranslate("Deal 2 damage, then reveal a mana card from the mana deck. If it's a 1 power mana card, place it on this spell"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_BASE_1,
],
 49 => [ 
  'name' => clienttranslate("Guilty bond"),
  'class' => "GuiltyBond",
  'description' => clienttranslate("Show your opponent a mana from your hand. Deal 2 damage if they have a mana of the same power in their hand"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_BASE_1,
  'js_actions' => "actionGuiltyBond",
],
 50 => [ 
  'name' => clienttranslate("Trance state"),
  'class' => "TranceState",
  'description' => clienttranslate("Deal 3 damage, minus 1 damage for each mana card in your hand"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_BASE_2,
],
 51 => [ 
  'name' => clienttranslate("Renewal"),
  'class' => "Renewal",
  'description' => clienttranslate("Gain mana until you have 4 mana cards in your hand"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_BASE_1,
],
 52 => [ 
  'name' => clienttranslate("Toxic gift"),
  'class' => "ToxicGift",
  'description' => clienttranslate("Give your opponent a mana card from your hand. If you do, deal damage equal to its power"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_BASE_1,
  'js_actions' => "actionToxicGift",
],
 53 => [ 
  'name' => clienttranslate("Wrath"),
  'class' => "Wrath",
  'description' => clienttranslate("Your opponent may discard 2 mana cards from their hand. If they do not, deal 2 damage"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_BASE_1,
  'interaction' => "opponent",
  'js_actions_interaction' => "actionWrath",
],
 54 => [ 
  'name' => clienttranslate("Reckless attack"),
  'class' => "RecklessAttack",
  'description' => clienttranslate("Deal 1 damage each time you discard off this spell. If you discard a 4 power mana off this spell, deal 4 damage instead"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_DELAYED,
  'activation_auto' => true,
  'cost' => 1,
  'icon' => WG_ICON_SET_BASE_2,
],
 55 => [ 
  'name' => clienttranslate("Shared power"),
  'class' => "SharedPower",
  'description' => clienttranslate("You may give your opponent 1 mana card from your hand. If you do, gain 4 mana cards"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_BASE_1,
  'js_actions' => "actionShadowPower",
],
 56 => [ 
  'name' => clienttranslate("Sleight of hand"),
  'class' => "SleightOfHand",
  'description' => clienttranslate("Gain 1 mana card. Gain additional mana equal to that mana's power"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_BASE_1,
],
 57 => [ 
  'name' => clienttranslate("Soul pact"),
  'class' => "SoulPact",
  'description' => clienttranslate("If the previous spell you cast this turn was an instant attack spell, gain mana equal to the damage dealt by that spell"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_BASE_2,
],
 58 => [ 
  'name' => clienttranslate("Mirror image"),
  'class' => "MirrorImage",
  'description' => clienttranslate("Gain mana equal to the quantity of mana cards on 1 of your spells"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_BASE_2,
  'js_actions' => "actionMirrorImage",
],
 59 => [ 
  'name' => clienttranslate("Battle vision"),
  'class' => "BattleVision",
  'description' => clienttranslate("When your opponent basic attacks, you may discard a mana card of the same power from your hand to block the damage"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_ONGOING,
  'cost' => 1,
  'icon' => WG_ICON_SET_BASE_2,
],
 60 => [ 
  'name' => clienttranslate("Silent support"),
  'class' => "SilentSupport",
  'description' => clienttranslate("Each time you discard off this spell, pick up a mana off 1 of your other spells"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_DELAYED,
  'activation_auto' => false,
  'cost' => 1,
  'icon' => WG_ICON_SET_BASE_2,
  'js_actions_delayed' => "actionSilentSupport",
],
 61 => [ 
  'name' => clienttranslate("Power hungry"),
  'class' => "PowerHungry",
  'description' => clienttranslate("Both players basic attack mana cards go to your hand instead of the discard pile"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_ONGOING,
  'cost' => 1,
  'icon' => WG_ICON_SET_BASE_1,
],
 62 => [ 
  'name' => clienttranslate("Sneaky deal"),
  'class' => "SneakyDeal",
  'description' => clienttranslate("Choose 1: Deal 1 damage, or discard a mana card off 1 of your other spells"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_BASE_1,
  'js_actions' => "actionSneakyDeal",
],
 63 => [ 
  'name' => clienttranslate("Puppetmaster"),
  'class' => "Puppetmaster",
  'description' => clienttranslate("In order to basic attack, your opponent must use a mana of the same power as you did during the previous basic attack phase"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_ONGOING,
  'cost' => 1,
  'icon' => WG_ICON_SET_BASE_2,
],
 64 => [ 
  'name' => clienttranslate("Contamination"),
  'class' => "Contamination",
  'description' => clienttranslate("Place 2 mana cards from your hand on the mana deck. If you do, deal 4 damage"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_2,
  'js_actions' => "actionContamination",
],
 65 => [ 
  'name' => clienttranslate("Dance of pain"),
  'class' => "DanceOfPain",
  'description' => clienttranslate("Deal 3 damage. Discard or gain mana until you have 2 mana cards in your hand"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_2,
  'js_actions' => "actionDanceOfPain",
],
 66 => [ 
  'name' => clienttranslate("Drain soul"),
  'class' => "DrainSoul",
  'description' => clienttranslate("Your opponent must give you the highest power card mana in their hand. Deal damage equal to that mana's power"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_1,
],
 67 => [ 
  'name' => clienttranslate("Ice storm"),
  'class' => "IceStorm",
  'description' => clienttranslate("Deal 1 damage for each of your spells with exactly 1 mana card on them"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_2,
],
 68 => [ 
  'name' => clienttranslate("After shock"),
  'class' => "AfterShock",
  'description' => clienttranslate("Gain 1 mana card. Place 1 mana card on the mana deck and deal damage equal to its power"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_2,
  'interaction' => "player",
  'js_actions_interaction' => "actionAfterShock",
],
 69 => [ 
  'name' => clienttranslate("Bad fortune"),
  'class' => "BadFortune",
  'description' => clienttranslate("Deal 4 damage. Reveal 3 cards from the mana deck. Place any revealed 1 power mana on this spell. Return the rest in any order"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_1,
  'interaction' => "player",
  'js_actions_interaction' => "actionBadFortune",
],
 70 => [ 
  'name' => clienttranslate("Force of nature"),
  'class' => "ForceOfNature",
  'description' => clienttranslate("Deal 4 damage, minus 1 damage for each of your other attack spells that have mana on them"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_BASE_2,
],
 101 => [ 
  'name' => clienttranslate("Backfire"),
  'class' => "Backfire",
  'description' => clienttranslate("Your opponent gains 1 mana card. They take damage equal to its power"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_SAND_1,
],
 102 => [ 
  'name' => clienttranslate("Echo"),
  'class' => "EchoCard",
  'description' => clienttranslate("Deal 3 damage. If you cast 1 of your other instant spells immediately before this and it cost 1 or less, this spell gains that spell's effect"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_SAND_1,
  'js_actions' => "actionEcho",
  'js_actions_interaction' => "actionEchoInteraction",
],
 103 => [ 
  'name' => clienttranslate("Invisible friend"),
  'class' => "InvisibleFriend",
  'description' => clienttranslate("Reveal 6 mana cards from the mana deck. Place the highest power mana back on the top of the mana deck. Gain the remaining 5 mana"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SAND_1,
],
 104 => [ 
  'name' => clienttranslate("Symbiosis"),
  'class' => "Symbiosis",
  'description' => clienttranslate("Gain a quantity of mana cards equal to the damage dealt by your opponent's previous basic attack"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_SAND_1,
],
 105 => [ 
  'name' => clienttranslate("Death spiral"),
  'class' => "DeathSpiral",
  'description' => clienttranslate("This spell costs 0 if the previous spell you cast cost 3 or more. Deal 2 damage"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SAND_1,
],
 106 => [ 
  'name' => clienttranslate("Transfigure"),
  'class' => "Transfigure",
  'description' => clienttranslate("Gain 4 mana. You may choose to gain 1 less mana to destroy 1 of your spells that has no mana on it"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SAND_1,
  'js_actions' => "actionTransfigure",
],
 107 => [ 
  'name' => clienttranslate("Shadow oath"),
  'class' => "ShadowOath",
  'description' => clienttranslate("Pick up a mana card off one of your other spells. You opponent gains 1 mana card"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_SAND_1,
  'js_actions' => "actionShadowOath",
],
 108 => [ 
  'name' => clienttranslate("Eclipse"),
  'class' => "Eclipse",
  'description' => clienttranslate("Reveal 3 mana cards from the mana deck, place them on any mix of your spells or your opponent's spells"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 4,
  'icon' => WG_ICON_SET_SAND_1,
  'interaction' => "player",
  'js_actions_interaction' => "actionEclipse",
],
 200 => [ 
  'name' => clienttranslate("Backfire"),
  'class' => "Backfire",
  'description' => clienttranslate("Your opponent gains 1 mana card. Deal damage equal to its power"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 201 => [ 
  'name' => clienttranslate("Mind games"),
  'class' => "MindGames",
  'description' => clienttranslate("Deal damage equal to the lowest power mana in your opponent's hand"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 202 => [ 
  'name' => clienttranslate("Psychic pain"),
  'class' => "PsychicPain",
  'description' => clienttranslate("Place 1 mana card from your hand on top of the mana deck. If you do, deal 2 damages"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
  'js_actions' => "actionPsychicPain",
],
 203 => [ 
  'name' => clienttranslate("Infinite flame"),
  'class' => "InfiniteFlame",
  'description' => clienttranslate("Your basic attack damage is increased by the quantity of mana on this spell"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_ONGOING,
  'cost' => 1,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 204 => [ 
  'name' => clienttranslate("Blank slate"),
  'class' => "BlankSlate",
  'description' => clienttranslate("When you discard off this spell, gain 3 mana. Pick up any remaining mana on this spell"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_DELAYED,
  'activation_auto' => true,
  'cost' => 1,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 205 => [ 
  'name' => clienttranslate("Crescendo"),
  'class' => "Crescendo",
  'description' => clienttranslate("The next time you cast a spell this turn, it costs 1 more and instantly gains you 4 mana cards"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 206 => [ 
  'name' => clienttranslate("Revelation"),
  'class' => "Revelation",
  'description' => clienttranslate("Reveal the top mana on 1 of your spells. Gain a quantity of mana equal to its power"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
  'js_actions' => "actionRevelation",
],
 207 => [ 
  'name' => clienttranslate("Rigmarole"),
  'class' => "Rigmarole",
  'description' => clienttranslate("Gain 1 mana card. Your opponent must give you the lowest power mana in their hand. You may give you opponent a mana from your hand"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 208 => [ 
  'name' => clienttranslate("Symbiosis"),
  'class' => "Symbiosis",
  'description' => clienttranslate("Gain a quantity of mana cards equal to the damage dealt by your opponent's previous basic attack"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 209 => [ 
  'name' => clienttranslate("Imagination"),
  'class' => "Imagination",
  'description' => clienttranslate("Choose 1: Gain 2 mana cards, or gain mana until you have the same quantity of mana cards as your opponent"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 210 => [ 
  'name' => clienttranslate("Devotion"),
  'class' => "Devotion",
  'description' => clienttranslate("Choose 1: Gain 2 mana cards, or discard a mana off 1 of your other spells"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 211 => [ 
  'name' => clienttranslate("Shadow oath"),
  'class' => "ShadowOath",
  'description' => clienttranslate("Pick up a mana card off one of your other spells. You opponent gains 1 mana card"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 1,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
  'js_actions' => "actionShadowOath",
],
 212 => [ 
  'name' => clienttranslate("Glass shield"),
  'class' => "GlassShield",
  'description' => clienttranslate("When your opponent basic attacks they must reveal a mana card of the same power in their hand in order to deal damage"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_ONGOING,
  'cost' => 1,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 213 => [ 
  'name' => clienttranslate("Fire walk"),
  'class' => "FireWalk",
  'description' => clienttranslate("Deal 4 damage. Place any 1 power mana still remaining in your hand onto this spell"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 214 => [ 
  'name' => clienttranslate("Brain drain"),
  'class' => "BrainDrain",
  'description' => clienttranslate("Deal damage equal to the lowest power mana in your hand"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 215 => [ 
  'name' => clienttranslate("Breathe fire"),
  'class' => "BreatheFire",
  'description' => clienttranslate("Deal 1 damage for each of your spells with exactly 2 mana cards on it"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 216 => [ 
  'name' => clienttranslate("Gloom"),
  'class' => "Gloom",
  'description' => clienttranslate("Deal 2 damage. You may take a mana of your choice from the discard pile and put it on 1 of your other spells"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 217 => [ 
  'name' => clienttranslate("Fever dream"),
  'class' => "FeverDream",
  'description' => clienttranslate("Whenever you add a spell to your spell repertoire, deal 2 damage"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_ONGOING,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 218 => [ 
  'name' => clienttranslate("Cursed mind"),
  'class' => "CursedMind",
  'description' => clienttranslate("The next time you cast a spell this turn, it costs 1 more and instantly deals 4 damage"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 219 => [ 
  'name' => clienttranslate("Ice blast"),
  'class' => "IceBlast",
  'description' => clienttranslate("Choose 1: Discard your hand and deal 5 damage, or place a mana card from the mana deck on 1 of your opponent's spells"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
  'js_actions' => "actionIceBlast",
],
 220 => [ 
  'name' => clienttranslate("Isolation"),
  'class' => "Isolation",
  'description' => clienttranslate("Deal 4 damage, minus 2 for each of your regeneration and utility spells that have mana on them"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 221 => [ 
  'name' => clienttranslate("Plague"),
  'class' => "Plague",
  'description' => clienttranslate("Deal 2 damage. You may deal 2 damage to yourself. If you do, gain 4 mana cards"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 222 => [ 
  'name' => clienttranslate("Dark offering"),
  'class' => "Dark Offering",
  'description' => clienttranslate("Pick up a mana card off 1 of your other spells and give it to your opponent. Dela damage equals to its power"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 223 => [ 
  'name' => clienttranslate("Belch"),
  'class' => "Belch",
  'description' => clienttranslate("Reveal 2 mana cards from the mana deck. Deal damage equal to the highest power mana revealed. Discard them or return them in any order"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 224 => [ 
  'name' => clienttranslate("Madness"),
  'class' => "Madness",
  'description' => clienttranslate("This spell costs 2 less if the previous spell you cast cost 3 or more. Deal 2 damage"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 225 => [ 
  'name' => clienttranslate("Wizard's gambit"),
  'class' => "WizardsGambit",
  'description' => clienttranslate("Deal 2 damage. Choose 1 of your spells. You may swap the mana on this spell with the chosen spell"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 226 => [ 
  'name' => clienttranslate("Earthquake"),
  'class' => "Earthquake",
  'description' => clienttranslate("Deal 2 damage for each card with unique mana power in your opponent's hand"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 227 => [ 
  'name' => clienttranslate("Restoration"),
  'class' => "Restoration",
  'description' => clienttranslate("Gain 4 mana cards. Gain 1 additionnal mana card for each attack spell cas consecutively before this spell"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 228 => [ 
  'name' => clienttranslate("Split soul"),
  'class' => "SplitSoul",
  'description' => clienttranslate("Choose 1: Gain 4 mana, or discard a mana card off 2 of your other spells"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
  'js_actions' => "actionSplitSoul",
],
 229 => [ 
  'name' => clienttranslate("Dream theft"),
  'class' => "DreamTheft",
  'description' => clienttranslate("Gain 3 mana. You opponent must give you the highest powermana in their hand"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 230 => [ 
  'name' => clienttranslate("Invisible friend"),
  'class' => "InvisibleFriend",
  'description' => clienttranslate("Reveal 6 mana cards from the mana deck. Place the highest power mana back on the top of the mana deck. Gain the remaining 5 mana"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 231 => [ 
  'name' => clienttranslate("Song of shadows"),
  'class' => "SongOfShadows",
  'description' => clienttranslate("Gain 5 mana. Give you opponent 1 mana card of your choice from the discard pile"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 232 => [ 
  'name' => clienttranslate("Transfigure"),
  'class' => "Transfigure",
  'description' => clienttranslate("Gain 4 mana. You may choose to gain 1 less mana to destroy 1 of your spells that has no mana on it. It is immediately replaced with a new spell"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
  'js_actions' => "actionTransfigure",
],
 233 => [ 
  'name' => clienttranslate("Rewind"),
  'class' => "Rewind",
  'description' => clienttranslate("Pick up mana off each of your other instant spells that have more than 1 mana on them"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 234 => [ 
  'name' => clienttranslate("Mask of the beast"),
  'class' => "MaskOfTheBeast",
  'description' => clienttranslate("Your opponent must discard their hand"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 235 => [ 
  'name' => clienttranslate("Second life"),
  'class' => "SecondLife",
  'description' => clienttranslate("Pick up a mana off 1 of your other spells. You may move a mana card between 2 of your other spells"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 236 => [ 
  'name' => clienttranslate("Sunken skull"),
  'class' => "SunkenSkull",
  'description' => clienttranslate("During your opponent's next turn, the power of all mana is decreased by 1"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 237 => [ 
  'name' => clienttranslate("Mirage"),
  'class' => "Mirage",
  'description' => clienttranslate("Pick up a mana off 1 of your other spells. If it is a 3 or higher power mana, deal 2 damage"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 238 => [ 
  'name' => clienttranslate("Premonition"),
  'class' => "Premonition",
  'description' => clienttranslate("The next 2 spells you cast this turn each cost 1 less"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 239 => [ 
  'name' => clienttranslate("Animal ambush"),
  'class' => "AnimalAmbush",
  'description' => clienttranslate("Deal 2 damage. You may place a mana from the mana deck on one of your opponent's spells"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 240 => [ 
  'name' => clienttranslate("Savage strike"),
  'class' => "SavageStrike",
  'description' => clienttranslate("Deal damage qual to the highest power mana used to cast this spell"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 2,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 241 => [ 
  'name' => clienttranslate("Living fire"),
  'class' => "LivingFire",
  'description' => clienttranslate("Deal 6 damage minus 1 for each of your other spells that have mana on them"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 242 => [ 
  'name' => clienttranslate("Raise the dead"),
  'class' => "RaiseTheDead",
  'description' => clienttranslate("Deal 6 damage. Place a mana from the mana deck on all of your other spells except 1 of your choice"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 243 => [ 
  'name' => clienttranslate("Multiply"),
  'class' => "Multiply",
  'description' => clienttranslate("As long as this spell has exactly 3 mana cards on it, your basic attack damage is doubled"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_ONGOING,
  'cost' => 3,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 244 => [ 
  'name' => clienttranslate("Exchange life"),
  'class' => "ExchangeLife",
  'description' => clienttranslate("Deal 3 damage. You may swap the mana cards in your hand with the mana cards in your opponent's hand"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_ONGOING,
  'cost' => 3,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 245 => [ 
  'name' => clienttranslate("Trample"),
  'class' => "Trample",
  'description' => clienttranslate("Deal 1 damage. Deal an additional 2 damage for each other spell you cast this turn that cost 3 or greater"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 246 => [ 
  'name' => clienttranslate("Cyclone"),
  'class' => "Cyclone",
  'description' => clienttranslate("Deal 3 damage. You may move a mana card between 2 of your other spells"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
  'js_actions' => "actionCyclone",
],
 247 => [ 
  'name' => clienttranslate("Corruption"),
  'class' => "Corruption",
  'description' => clienttranslate("Deal damage equal to the quantity of mana cards on 1 of your other spells. Then discard 2 mana cards off  of it"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 248 => [ 
  'name' => clienttranslate("Transference"),
  'class' => "Transference",
  'description' => clienttranslate("Gain 6 mana. You may gain 4 less mana to destroy another spell. After the spell is destroyed, the owner of the spell replaces it"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 249 => [ 
  'name' => clienttranslate("Spirit dance"),
  'class' => "SpiritDance",
  'description' => clienttranslate("Gain 6 mana. You may gain 2 less mana to move a mana between 2 of your opponent's spells"),
  'type' => WG_SPELL_TYPE_REGENERATION,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
  'js_actions' => "actionSpiritDance",
],
 250 => [ 
  'name' => clienttranslate("Blossom"),
  'class' => "Blossom",
  'description' => clienttranslate("As long as this spell has exactly 3 mana cards on it, increase the power of all mana by 2 during your turn"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 251 => [ 
  'name' => clienttranslate("Seeing stone"),
  'class' => "SeeingStone",
  'description' => clienttranslate("Loot at the top 4 spells of the spell deck; you may choose 1 to replace this spell. Return all remaining spells in an order of your choosing"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
 252 => [ 
  'name' => clienttranslate("Crystal shard"),
  'class' => "CrystalShard",
  'description' => clienttranslate("Add this Relic to your hand. Treat it as a 5 power mana. Once discarded, it goes to the spell discard"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 253 => [ 
  'name' => clienttranslate("Frozen goblet"),
  'class' => "FrozenGoblet",
  'description' => clienttranslate("Your opponent gains only1 mana at the start of their next turn"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 3,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 254 => [ 
  'name' => clienttranslate("Dance of agony"),
  'class' => "DanceOfAgony",
  'description' => clienttranslate("Deal 4 damage. Discard or gain mana until you have 4 cards in your hand"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 4,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
  'js_actions' => "actionDanceOfAgony",
],
 255 => [ 
  'name' => clienttranslate("Death Spiral"),
  'class' => "DeathSpiral",
  'description' => clienttranslate("Each time you discard off this spell, deal 1 damage for each mana remaining on it"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_DELAYED,
  'activation_auto' => true,
  'cost' => 4,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 256 => [ 
  'name' => clienttranslate("Soul shatter"),
  'class' => "SoulShatter",
  'description' => clienttranslate("Deal 4 damage. Deal additional damage equal to the highest power mana in your opponent's hand"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 4,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 257 => [ 
  'name' => clienttranslate("Eclipse"),
  'class' => "Eclipse",
  'description' => clienttranslate("Reveal 3 mana cards from the mana deck, place them on any mix of your spells or your opponent's spells"),
  'type' => WG_SPELL_TYPE_UTILITY,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 4,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
  'interaction' => "player",
  'js_actions_interaction' => "actionEclipse",
],
 258 => [ 
  'name' => clienttranslate("Unchained"),
  'class' => "Unchained",
  'description' => clienttranslate("Choose 1: Deal 5 damage, or gain 5 health"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 5,
  'icon' => WG_ICON_SET_SHIFTING_SAND_1,
],
 259 => [ 
  'name' => clienttranslate("Sandstorm"),
  'class' => "Sandstorm",
  'description' => clienttranslate("This spell costs 1 less for each consecutive regeneration and utility spell cast before this spell. Deal 4 damage"),
  'type' => WG_SPELL_TYPE_ATTACK,
  'activation' => WG_SPELL_ACTIVATION_INSTANT,
  'cost' => 5,
  'icon' => WG_ICON_SET_SHIFTING_SAND_2,
],
  // --- gen php end --- 
];

$this->mana_cards = [
  1 => 32,
  2 => 16,
  3 => 8,
  4 => 4,
];
